services:
    - type: web
      name: my-python-app
      repo: https://github.com/daveckw/custom-data-chatgpt-with-langchain-agent.git
      env: python
      build:
          env:
              PYTHON_VERSION: 3.10
      buildCommand: pip install -r requirements.txt
      startCommand: ./gunicorn_start.sh
